name: "Terraform Peering Fix"

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  terraform:
    name: "Terraform Build"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      - name: Terraform Force Unlock
        run: terraform force-unlock -force 1772087979567042
        working-directory: ./environments/prod
        continue-on-error: true  # So the workflow keeps going if the lock is already gone

      - name: Terraform Init
        run: terraform init
        working-directory: ./environments/prod

